apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "\"traceId\"\\s*:\\s*\"(\\w+)\""
          name: TraceID
          url: "$${__value.raw}"
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        tags:
          - key: 'service.name'
            value: 'service'
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{compose_project="event-driven-fraud-detection",$${__tags}} | json | traceId="$${__trace.traceId}"'
      tracesToMetrics:
        datasourceUid: prometheus
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
  - name: alert-db
    uid: alert-db
    type: postgres
    access: proxy
    url: alert-db:5432
    user: postgres
    editable: true
    jsonData:
      database: alerts
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: postgres
