global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: spring-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - transaction-service:8080
          - fraud-detection-service:8081
          - alert-service:8082

  - job_name: kafka-exporter
    static_configs:
      - targets:
          - kafka-exporter:9308

  - job_name: postgres-exporters
    static_configs:
      - targets:
          - transaction-db-exporter:9187
        labels:
          db_service: transaction-db
          db_name: transactions
      - targets:
          - fraud-db-exporter:9187
        labels:
          db_service: fraud-db
          db_name: fraud
      - targets:
          - alert-db-exporter:9187
        labels:
          db_service: alert-db
          db_name: alerts

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
