worker_processes auto;

events {
  worker_connections 1024;
}

http {
  resolver 127.0.0.11 valid=10s ipv6=off;

  upstream alert_service {
    zone alert_service 64k;
    server alert-service:8082 resolve;
    keepalive 256;
  }

  server {
    listen 8082;
    server_name _;

    location / {
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Connection "";
      proxy_pass http://alert_service;
    }
  }
}
